title: Probot
description: GitHub Apps to automate and improve your workflow
permalink: pretty

exclude:
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - _submodules
  - script
  - vendor

markdown: GFM

sass:
  style: :compressed
  sass_dir: _sass
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

collections:
  apps:
    output: true
    permalink: /apps/:name/

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: app
  - scope:
      path: "docs"
    values:
      layout: docs

plugins:
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

branch: master
